# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               James Liu
tagline:             ''
description:         ''
url:                 https://blog.jamesliu.ca
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              James Liu
  url:               https://jamesliu.ca
  email:             james@jamesliu.ca

# Custom vars
version:             0.1.0
